# Generated Thu Oct 06 17:12:30 2016
d = {}
d[''] = {
    'number': 112,
    'setting': '',
    'point_group': '-42m',
    'laue_group': '4/mmm',
    'order': 8,
    'order_p': 8,
    'unique_axis': 'z',
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hhl: l=2n',
        'h-hl: l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hhl: e=2',
        'h-hl: e=2',
        'h00: e=2',
        '0k0: e=2',
        '00l: e=4',
    ),
    'phase_restrictions': (
        'hk0: 0 deg',
        'h0l: 90 deg (l)',
        '0kl: 90 deg (l)',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        'y, -x, -z',
        '-x, -y, z',
        '-y, x, -z',
        'x, -y, -z+1/2',
        '-x, y, -z+1/2',
        '-y, -x, z+1/2',
        'y, x, z+1/2',
    ),
    'wyckoff_positions' : (
        (2, '0,0,1/4'),
        (2, '1/2,0,1/4'),
        (2, '1/2,1/2,1/4'),
        (2, '0,1/2,1/4'),
        (2, '0,0,0'),
        (2, '1/2,1/2,0'),
        (4, 'x,0,1/4'),
        (4, '1/2,y,1/4'),
        (4, 'x,1/2,1/4'),
        (4, '0,y,1/4'),
        (4, '0,0,z'),
        (4, '1/2,1/2,z'),
        (4, '0,1/2,z'),
        (8, 'x, y, z'),
    )
}
