# Generated Thu Oct 06 17:12:31 2016
d = {}
d['1'] = {
    'number': 129,
    'setting': '1',
    'point_group': '4/mmm',
    'laue_group': '4/mmm',
    'order': 16,
    'order_p': 16,
    'unique_axis': 'z',
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hk0: h+k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hhl: e=2',
        'hk0: e=2',
        'h0l: e=2',
        'h-hl: e=2',
        '0kl: e=2',
        'hh0: e=4',
        'h00: e=4',
        'h-h0: e=4',
        '0k0: e=4',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 90 deg (h+k)',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-x+1/2, -y+1/2, -z',
        '-y+1/2, x+1/2, z',
        '-x, -y, z',
        'y+1/2, -x+1/2, z',
        'y, -x, -z',
        '-y, x, -z',
        'x+1/2, -y+1/2, -z',
        '-x+1/2, y+1/2, -z',
        'y, x, -z',
        '-y, -x, -z',
        'x+1/2, y+1/2, -z',
        '-x, y, z',
        'x, -y, z',
        '-y+1/2, -x+1/2, z',
        'y+1/2, x+1/2, z',
    ),
    'wyckoff_positions' : (
        (2, '-1/4,1/4,0'),
        (2, '-1/4,1/4,1/2'),
        (2, '1/4,1/4,z'),
        (4, '0,0,0'),
        (4, '0,0,1/2'),
        (4, '-1/4,1/4,z'),
        (8, '1/2*x-1/2*y,-1/2*x+1/2*y,0'),
        (8, '1/2*x-1/2*y,-1/2*x+1/2*y,1/2'),
        (8, '1/4,y,z'),
        (8, '1/2*x+1/2*y,1/2*x+1/2*y,z'),
        (16, 'x, y, z'),
    )
}

d['2'] = {
    'number': 129,
    'setting': '2',
    'point_group': '4/mmm',
    'laue_group': '4/mmm',
    'order': 16,
    'order_p': 16,
    'unique_axis': 'z',
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hk0: h+k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hhl: e=2',
        'hk0: e=2',
        'h0l: e=2',
        'h-hl: e=2',
        '0kl: e=2',
        'hh0: e=4',
        'h00: e=4',
        'h-h0: e=4',
        '0k0: e=4',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-y+1/2, x, z',
        '-x+1/2, -y+1/2, z',
        'y, -x+1/2, z',
        'x+1/2, -y, -z',
        '-x, y+1/2, -z',
        'y+1/2, x+1/2, -z',
        '-y, -x, -z',
    ),
    'wyckoff_positions' : (
        (2, '-1/4,1/4,0'),
        (2, '-1/4,1/4,1/2'),
        (2, '1/4,1/4,z'),
        (4, '0,0,0'),
        (4, '0,0,1/2'),
        (4, '-1/4,1/4,z'),
        (8, '1/2*x-1/2*y,-1/2*x+1/2*y,0'),
        (8, '1/2*x-1/2*y,-1/2*x+1/2*y,1/2'),
        (8, '1/4,y,z'),
        (8, '1/2*x+1/2*y,1/2*x+1/2*y,z'),
        (16, 'x, y, z'),
    )
}
