# Generated Thu Oct 06 17:12:35 2016
d = {}
d[''] = {
    'number': 188,
    'setting': '',
    'point_group': '-6m2',
    'laue_group': '6/mmm',
    'order': 12,
    'order_p': 12,
    'unique_axis': 'z',
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'h0l: l=2n',
        'h-hl: l=2n',
        '0kl: l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hk0: e=2',
        'h0l: e=2',
        'h-hl: e=2',
        '0kl: e=2',
        'h00: e=4',
        'h-h0: e=4',
        '0k0: e=4',
        '00l: e=6',
    ),
    'phase_restrictions': (
        'hhl: 0 deg',
        'h-2hl: 0 deg',
        '-2kkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-x+y, -x, -z+1/2',
        '-y, x-y, z',
        'x, y, -z+1/2',
        '-x+y, -x, z',
        '-y, x-y, -z+1/2',
        '-y, -x, -z',
        '-x+y, y, -z',
        'x, x-y, -z',
        '-x+y, y, z+1/2',
        'x, x-y, z+1/2',
        '-y, -x, z+1/2',
    ),
    'wyckoff_positions' : (
        (2, '0,0,0'),
        (2, '0,0,1/4'),
        (2, '1/3,-1/3,0'),
        (2, '1/3,-1/3,1/4'),
        (2, '-1/3,1/3,0'),
        (2, '-1/3,1/3,1/4'),
        (4, '0,0,z'),
        (4, '1/3,-1/3,z'),
        (4, '-1/3,1/3,z'),
        (6, '1/2*x-1/2*y,-1/2*x+1/2*y,0'),
        (6, 'x,y,1/4'),
        (12, 'x, y, z'),
    )
}
