# Generated Thu Oct 06 17:12:35 2016
d = {}
d[''] = {
    'number': 190,
    'setting': '',
    'point_group': '-62m',
    'laue_group': '6/mmm',
    'order': 12,
    'order_p': 12,
    'unique_axis': 'z',
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hhl: l=2n',
        'h-2hl: l=2n',
        '-2kkl: l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hhl: e=2',
        'hk0: e=2',
        'h-2hl: e=2',
        '-2kkl: e=2',
        'hh0: e=4',
        'h-2h0: e=4',
        '00l: e=6',
        '-2kk0: e=4',
    ),
    'phase_restrictions': (
        'h0l: 0 deg',
        'h-hl: 0 deg',
        '0kl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-x+y, -x, -z+1/2',
        '-y, x-y, z',
        'x, y, -z+1/2',
        '-x+y, -x, z',
        '-y, x-y, -z+1/2',
        'x-y, -y, -z',
        '-x, -x+y, -z',
        'y, x, -z',
        'y, x, z+1/2',
        'x-y, -y, z+1/2',
        '-x, -x+y, z+1/2',
    ),
    'wyckoff_positions' : (
        (2, '0,0,0'),
        (2, '0,0,1/4'),
        (2, '1/3,-1/3,1/4'),
        (2, '-1/3,1/3,1/4'),
        (4, '0,0,z'),
        (4, '1/3,-1/3,z'),
        (6, 'x-1/2*y,0,0'),
        (6, 'x,y,1/4'),
        (12, 'x, y, z'),
    )
}
