# Generated Mon Apr 25 10:54:45 2016
d = {}
d[''] = {
    'number': 191,
    'setting': '',
    'point_group': '6/mmm',
    'laue_group': '6/mmm',
    'order': 24,
    'order_p': 24,
    'unique_axis': 'z',
    'centrosymmetric': True,
    'reflection_conditions': (
        'hkl: No Condition',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        'x-y, x, z',
        '-y, x-y, z',
        '-x, -y, z',
        '-x+y, -x, z',
        'y, -x+y, z',
        'x-y, -y, -z',
        '-x, -x+y, -z',
        'y, x, -z',
        '-y, -x, -z',
        '-x+y, y, -z',
        'x, x-y, -z',
    ),
    'wyckoff_positions' : (
        (1, '0,0,0'),
        (1, '0,0,1/2'),
        (2, '1/3,-1/3,0'),
        (2, '1/3,-1/3,1/2'),
        (2, '0,0,z'),
        (3, '1/2,0,0'),
        (3, '1/2,0,1/2'),
        (4, '1/3,-1/3,z'),
        (6, '1/2,0,z'),
        (6, 'x-1/2*y,0,0'),
        (6, 'x-1/2*y,0,1/2'),
        (6, '1/2*y,y,0'),
        (6, '1/2*y,y,1/2'),
        (12, 'x-1/2*y,0,z'),
        (12, '1/2*y,y,z'),
        (12, 'x,y,0'),
        (12, 'x,y,1/2'),
        (24, 'x, y, z'),
    )
}
