# Generated Thu Oct 06 17:12:35 2016
d = {}
d[''] = {
    'number': 192,
    'setting': '',
    'point_group': '6/mmm',
    'laue_group': '6/mmm',
    'order': 24,
    'order_p': 24,
    'unique_axis': 'z',
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hhl: l=2n',
        'h0l: l=2n',
        'h-hl: l=2n',
        'h-2hl: l=2n',
        '0kl: l=2n',
        '-2kkl: l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hhl: e=2',
        'hk0: e=2',
        'h0l: e=2',
        'h-hl: e=2',
        'h-2hl: e=2',
        '0kl: e=2',
        '-2kkl: e=2',
        'hh0: e=4',
        'h00: e=4',
        'h-h0: e=4',
        'h-2h0: e=4',
        '0k0: e=4',
        '00l: e=12',
        '-2kk0: e=4',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        'x-y, x, z',
        '-y, x-y, z',
        '-x, -y, z',
        '-x+y, -x, z',
        'y, -x+y, z',
        'x-y, -y, -z+1/2',
        '-x, -x+y, -z+1/2',
        'y, x, -z+1/2',
        '-y, -x, -z+1/2',
        '-x+y, y, -z+1/2',
        'x, x-y, -z+1/2',
    ),
    'wyckoff_positions' : (
        (2, '0,0,1/4'),
        (2, '0,0,0'),
        (4, '1/3,-1/3,1/4'),
        (4, '1/3,-1/3,0'),
        (4, '0,0,z'),
        (6, '1/2,0,1/4'),
        (6, '1/2,0,0'),
        (8, '1/3,-1/3,z'),
        (12, '1/2,0,z'),
        (12, 'x-1/2*y,0,1/4'),
        (12, '1/2*y,y,1/4'),
        (12, 'x,y,0'),
        (24, 'x, y, z'),
    )
}
