# Generated Thu Oct 06 17:12:35 2016
d = {}
d[''] = {
    'number': 195,
    'setting': '',
    'point_group': '23',
    'laue_group': 'm-3',
    'order': 12,
    'order_p': 12,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': True,
    'obverse': False,
    'reflection_conditions': (
        'hkl: No Condition',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hhh: e=3',
        'hh-h: e=3',
        'h00: e=2',
        'h-hh: e=3',
        'h-h-h: e=3',
        '0k0: e=2',
        '00l: e=2',
    ),
    'phase_restrictions': (
        'hk0: 0 deg',
        'h0l: 0 deg',
        '0kl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
    ),
    'wyckoff_positions' : (
        (1, '0,0,0'),
        (1, '1/2,1/2,1/2'),
        (3, '0,1/2,1/2'),
        (3, '1/2,0,0'),
        (4, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (6, 'x,0,0'),
        (6, 'x,0,1/2'),
        (6, 'x,1/2,0'),
        (6, 'x,1/2,1/2'),
        (12, 'x, y, z'),
    )
}
