# Generated Thu Oct 06 17:12:35 2016
d = {}
d[''] = {
    'number': 202,
    'setting': '',
    'point_group': 'm-3',
    'laue_group': 'm-3',
    'order': 96,
    'order_p': 24,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k=2n',
        'hkl: h+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=4',
        'hk0: e=8',
        'h0l: e=8',
        '0kl: e=8',
        'hhh: e=12',
        'hh-h: e=12',
        'h00: e=16',
        'h-hh: e=12',
        'h-h-h: e=12',
        '0k0: e=16',
        '00l: e=16',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
        [0.5, 0.0, 0.5],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
    ),
    'wyckoff_positions' : (
        (4, '0,0,0'),
        (4, '1/2,1/2,1/2'),
        (8, '1/4,1/4,1/4'),
        (24, '0,1/4,1/4'),
        (24, 'x,0,0'),
        (32, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (48, 'x,1/4,1/4'),
        (48, '0,y,z'),
        (96, 'x, y, z'),
    )
}
