# Generated Thu Oct 06 17:12:36 2016
d = {}
d[''] = {
    'number': 206,
    'setting': '',
    'point_group': 'm-3',
    'laue_group': 'm-3',
    'order': 48,
    'order_p': 24,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k+l=2n',
        'hk0: h=2n',
        'h0l: h=2n',
        '0kl: k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'hhh: e=6',
        'hh-h: e=6',
        'h00: e=8',
        'h-hh: e=6',
        'h-h-h: e=6',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        'z, x, y',
        'y, z, x',
        '-y, -z+1/2, x',
        'z, -x, -y+1/2',
        '-y+1/2, z, -x',
        '-z, -x+1/2, y',
        '-z+1/2, x, -y',
        'y, -z, -x+1/2',
        '-x, -y+1/2, z',
        'x, -y, -z+1/2',
        '-x+1/2, y, -z',
    ),
    'wyckoff_positions' : (
        (8, '0,0,0'),
        (8, '1/4,1/4,1/4'),
        (16, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (24, 'x,0,1/4'),
        (48, 'x, y, z'),
    )
}
