# Generated Thu Oct 06 17:12:36 2016
d = {}
d[''] = {
    'number': 207,
    'setting': '',
    'point_group': '432',
    'laue_group': 'm-3m',
    'order': 24,
    'order_p': 24,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': True,
    'obverse': False,
    'reflection_conditions': (
        'hkl: No Condition',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hhh: e=3',
        'hh0: e=2',
        'hh-h: e=3',
        'h0h: e=2',
        'h00: e=4',
        'h0-h: e=2',
        'h-hh: e=3',
        'h-h0: e=2',
        'h-h-h: e=3',
        '0kk: e=2',
        '0k0: e=4',
        '0k-k: e=2',
        '00l: e=4',
    ),
    'phase_restrictions': (
        'hhl: 0 deg',
        'hkh: 0 deg',
        'hkk: 0 deg',
        'hk0: 0 deg',
        'hk-k: 0 deg',
        'h0l: 0 deg',
        'hk-h: 0 deg',
        'h-hl: 0 deg',
        '0kl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-y, x, z',
        '-x, -y, z',
        'y, -x, z',
        'x, -z, y',
        'x, -y, -z',
        'x, z, -y',
        'z, y, -x',
        '-x, y, -z',
        '-z, y, x',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        'y, x, -z',
        '-y, -x, -z',
        '-x, z, y',
        '-x, -z, -y',
        'z, -y, x',
        '-z, -y, -x',
    ),
    'wyckoff_positions' : (
        (1, '0,0,0'),
        (1, '1/2,1/2,1/2'),
        (3, '0,1/2,1/2'),
        (3, '1/2,0,0'),
        (6, 'x,0,0'),
        (6, 'x,1/2,1/2'),
        (8, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (12, 'x,1/2,0'),
        (12, '0,1/2*y+1/2*z,1/2*y+1/2*z'),
        (12, '1/2,1/2*y+1/2*z,1/2*y+1/2*z'),
        (24, 'x, y, z'),
    )
}
