# Generated Thu Oct 06 17:12:36 2016
d = {}
d[''] = {
    'number': 216,
    'setting': '',
    'point_group': '-43m',
    'laue_group': 'm-3m',
    'order': 96,
    'order_p': 24,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k=2n',
        'hkl: h+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=4',
        'hhl: e=8',
        'hkh: e=8',
        'hkk: e=8',
        'hk-k: e=8',
        'hk-h: e=8',
        'h-hl: e=8',
        'hhh: e=24',
        'hh-h: e=24',
        'h00: e=16',
        'h-hh: e=24',
        'h-h-h: e=24',
        '0k0: e=16',
        '00l: e=16',
    ),
    'phase_restrictions': (
        'hk0: 0 deg',
        'h0l: 0 deg',
        '0kl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
        [0.5, 0.0, 0.5],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        'y, -x, -z',
        '-x, -y, z',
        '-y, x, -z',
        '-x, z, -y',
        'x, -y, -z',
        '-x, -z, y',
        '-z, -y, x',
        '-x, y, -z',
        'z, -y, -x',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        '-y, -x, z',
        'y, x, z',
        'x, -z, -y',
        'x, z, y',
        '-z, y, -x',
        'z, y, x',
    ),
    'wyckoff_positions' : (
        (4, '0,0,0'),
        (4, '1/2,1/2,1/2'),
        (4, '1/4,1/4,1/4'),
        (4, '-1/4,-1/4,-1/4'),
        (16, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (24, 'x,0,0'),
        (24, 'x,1/4,1/4'),
        (48, '1/2*x+1/2*y,1/2*x+1/2*y,z'),
        (96, 'x, y, z'),
    )
}
