# Generated Thu Oct 06 17:12:36 2016
d = {}
d[''] = {
    'number': 218,
    'setting': '',
    'point_group': '-43m',
    'laue_group': 'm-3m',
    'order': 24,
    'order_p': 24,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hhl: l=2n',
        'hkh: k=2n',
        'hkk: h=2n',
        'hk-k: h=2n',
        'hk-h: k=2n',
        'h-hl: l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=1',
        'hhl: e=2',
        'hkh: e=2',
        'hkk: e=2',
        'hk-k: e=2',
        'hk-h: e=2',
        'h-hl: e=2',
        'hhh: e=6',
        'hh-h: e=6',
        'h00: e=4',
        'h-hh: e=6',
        'h-h-h: e=6',
        '0k0: e=4',
        '00l: e=4',
    ),
    'phase_restrictions': (
        'hk0: 0 deg',
        'h0l: 0 deg',
        '0kl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        'y+1/2, -x+1/2, -z+1/2',
        '-x, -y, z',
        '-y+1/2, x+1/2, -z+1/2',
        '-x+1/2, z+1/2, -y+1/2',
        'x, -y, -z',
        '-x+1/2, -z+1/2, y+1/2',
        '-z+1/2, -y+1/2, x+1/2',
        '-x, y, -z',
        'z+1/2, -y+1/2, -x+1/2',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        '-y+1/2, -x+1/2, z+1/2',
        'y+1/2, x+1/2, z+1/2',
        'x+1/2, -z+1/2, -y+1/2',
        'x+1/2, z+1/2, y+1/2',
        '-z+1/2, y+1/2, -x+1/2',
        'z+1/2, y+1/2, x+1/2',
    ),
    'wyckoff_positions' : (
        (2, '0,0,0'),
        (6, '0,1/2,1/2'),
        (6, '1/4,1/2,0'),
        (6, '1/4,0,1/2'),
        (8, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (12, 'x,0,0'),
        (12, 'x,1/2,0'),
        (12, 'x,0,1/2'),
        (24, 'x, y, z'),
    )
}
