# Generated Mon Apr 25 10:54:47 2016
d = {}
d[''] = {
    'number': 219,
    'setting': '',
    'point_group': '-43m',
    'laue_group': 'm-3m',
    'order': 96,
    'order_p': 24,
    'unique_axis': None,
    'centrosymmetric': False,
    'reflection_conditions': (
        'hkl: h+k=2n',
        'hkl: h+l=2n',
        'hhl: h=2n',
        'hkh: h=2n',
        'hkk: h=2n',
        'hk-k: h=2n',
        'hk-h: h=2n',
        'h-hl: h=2n',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
        [0.5, 0.0, 0.5],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        'y, -x, -z+1/2',
        '-x, -y, z',
        '-y, x, -z+1/2',
        '-x, z, -y+1/2',
        'x, -y, -z',
        '-x, -z, y+1/2',
        '-z, -y, x+1/2',
        '-x, y, -z',
        'z, -y, -x+1/2',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        '-y, -x, z+1/2',
        'y, x, z+1/2',
        'x, -z, -y+1/2',
        'x, z, y+1/2',
        '-z, y, -x+1/2',
        'z, y, x+1/2',
    ),
    'wyckoff_positions' : (
        (8, '0,0,0'),
        (8, '1/4,1/4,1/4'),
        (24, '0,1/4,1/4'),
        (24, '1/4,0,0'),
        (32, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (48, 'x,0,0'),
        (48, 'x,1/4,1/4'),
        (96, 'x, y, z'),
    )
}
