# Generated Thu Oct 06 10:30:43 2016
d = {}
d[''] = {
    'number': 221,
    'setting': '',
    'point_group': 'm-3m',
    'laue_group': 'm-3m',
    'order': 48,
    'order_p': 48,
    'unique_axis': None,
    'centrosymmetric': True,
    'reflection_conditions': (
        'hkl: No Condition',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-y, x, z',
        '-x, -y, z',
        'y, -x, z',
        'x, -z, y',
        'x, -y, -z',
        'x, z, -y',
        'z, y, -x',
        '-x, y, -z',
        '-z, y, x',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        'y, x, -z',
        '-y, -x, -z',
        '-x, z, y',
        '-x, -z, -y',
        'z, -y, x',
        '-z, -y, -x',
    ),
    'wyckoff_positions' : (
        (1, '0,0,0'),
        (1, '1/2,1/2,1/2'),
        (3, '0,1/2,1/2'),
        (3, '1/2,0,0'),
        (6, 'x,0,0'),
        (6, 'x,1/2,1/2'),
        (8, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (12, 'x,1/2,0'),
        (12, '0,1/2*y+1/2*z,1/2*y+1/2*z'),
        (12, '1/2,1/2*y+1/2*z,1/2*y+1/2*z'),
        (24, '0,y,z'),
        (24, '1/2,y,z'),
        (24, '1/2*x+1/2*y,1/2*x+1/2*y,z'),
        (48, 'x, y, z'),
    )
}
