# Generated Thu Oct 06 17:12:37 2016
d = {}
d[''] = {
    'number': 226,
    'setting': '',
    'point_group': 'm-3m',
    'laue_group': 'm-3m',
    'order': 192,
    'order_p': 48,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k=2n',
        'hkl: h+l=2n',
        'hhl: h=2n',
        'hkh: h=2n',
        'hkk: h=2n',
        'hk-k: h=2n',
        'hk-h: h=2n',
        'h-hl: h=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=4',
        'hhl: e=8',
        'hkh: e=8',
        'hkk: e=8',
        'hk0: e=8',
        'hk-k: e=8',
        'h0l: e=8',
        'hk-h: e=8',
        'h-hl: e=8',
        '0kl: e=8',
        'hhh: e=24',
        'hh0: e=16',
        'hh-h: e=24',
        'h0h: e=16',
        'h00: e=32',
        'h0-h: e=16',
        'h-hh: e=24',
        'h-h0: e=16',
        'h-h-h: e=24',
        '0kk: e=16',
        '0k0: e=32',
        '0k-k: e=16',
        '00l: e=32',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
        [0.5, 0.0, 0.5],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-y, x, z+1/2',
        '-x, -y, z',
        'y, -x, z+1/2',
        'x, -z, y+1/2',
        'x, -y, -z',
        'x, z, -y+1/2',
        'z, y, -x+1/2',
        '-x, y, -z',
        '-z, y, x+1/2',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        'y, x, -z+1/2',
        '-y, -x, -z+1/2',
        '-x, z, y+1/2',
        '-x, -z, -y+1/2',
        'z, -y, x+1/2',
        '-z, -y, -x+1/2',
    ),
    'wyckoff_positions' : (
        (8, '1/4,1/4,1/4'),
        (8, '0,0,0'),
        (24, '1/4,0,0'),
        (24, '0,1/4,1/4'),
        (48, 'x,0,0'),
        (48, 'x,1/4,1/4'),
        (64, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (96, '1/4,1/2*y+1/2*z,1/2*y+1/2*z'),
        (96, '0,y,z'),
        (192, 'x, y, z'),
    )
}
