# Generated Mon Apr 25 10:54:48 2016
d = {}
d[''] = {
    'number': 229,
    'setting': '',
    'point_group': 'm-3m',
    'laue_group': 'm-3m',
    'order': 96,
    'order_p': 48,
    'unique_axis': None,
    'centrosymmetric': True,
    'reflection_conditions': (
        'hkl: h+k+l=2n',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-y, x, z',
        '-x, -y, z',
        'y, -x, z',
        'x, -z, y',
        'x, -y, -z',
        'x, z, -y',
        'z, y, -x',
        '-x, y, -z',
        '-z, y, x',
        'z, x, y',
        'y, z, x',
        '-y, -z, x',
        'z, -x, -y',
        '-y, z, -x',
        '-z, -x, y',
        '-z, x, -y',
        'y, -z, -x',
        'y, x, -z',
        '-y, -x, -z',
        '-x, z, y',
        '-x, -z, -y',
        'z, -y, x',
        '-z, -y, -x',
    ),
    'wyckoff_positions' : (
        (2, '0,0,0'),
        (6, '0,1/2,1/2'),
        (8, '1/4,1/4,1/4'),
        (12, '1/4,0,1/2'),
        (12, 'x,0,0'),
        (16, '1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z,1/3*x+1/3*y+1/3*z'),
        (24, 'x,0,1/2'),
        (24, '0,1/2*y+1/2*z,1/2*y+1/2*z'),
        (48, '1/4,1/2*y-1/2*z+1/4,-1/2*y+1/2*z+1/4'),
        (48, '0,y,z'),
        (48, '1/2*x+1/2*y,1/2*x+1/2*y,z'),
        (96, 'x, y, z'),
    )
}
