# Generated Thu Oct 06 10:30:32 2016
d = {}
d[''] = {
    'number': 65,
    'setting': '',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'reflection_conditions': (
        'hkl: h+k=2n',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
    ),
    'wyckoff_positions' : (
        (2, '0,0,0'),
        (2, '1/2,0,0'),
        (2, '1/2,0,1/2'),
        (2, '0,0,1/2'),
        (4, '1/4,1/4,0'),
        (4, '1/4,1/4,1/2'),
        (4, 'x,0,0'),
        (4, 'x,0,1/2'),
        (4, '0,y,0'),
        (4, '0,y,1/2'),
        (4, '0,0,z'),
        (4, '0,1/2,z'),
        (8, '1/4,1/4,z'),
        (8, '0,y,z'),
        (8, 'x,0,z'),
        (8, 'x,y,0'),
        (8, 'x,y,1/2'),
        (16, 'x, y, z'),
    )
}

d['cab'] = {
    'number': 65,
    'setting': 'cab',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'reflection_conditions': (
        'hkl: k+l=2n',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
    ),
    'wyckoff_positions' : (
        (2, '0,0,0'),
        (2, '1/2,0,0'),
        (2, '1/2,0,1/2'),
        (2, '0,0,1/2'),
        (4, '1/4,1/4,0'),
        (4, '1/4,1/4,1/2'),
        (4, 'x,0,0'),
        (4, 'x,0,1/2'),
        (4, '0,y,0'),
        (4, '0,y,1/2'),
        (4, '0,0,z'),
        (4, '0,1/2,z'),
        (8, '1/4,1/4,z'),
        (8, '0,y,z'),
        (8, 'x,0,z'),
        (8, 'x,y,0'),
        (8, 'x,y,1/2'),
        (16, 'x, y, z'),
    )
}

d['bca'] = {
    'number': 65,
    'setting': 'bca',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'reflection_conditions': (
        'hkl: h+l=2n',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.0, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
    ),
    'wyckoff_positions' : (
        (2, '0,0,0'),
        (2, '1/2,0,0'),
        (2, '1/2,0,1/2'),
        (2, '0,0,1/2'),
        (4, '1/4,1/4,0'),
        (4, '1/4,1/4,1/2'),
        (4, 'x,0,0'),
        (4, 'x,0,1/2'),
        (4, '0,y,0'),
        (4, '0,y,1/2'),
        (4, '0,0,z'),
        (4, '0,1/2,z'),
        (8, '1/4,1/4,z'),
        (8, '0,y,z'),
        (8, 'x,0,z'),
        (8, 'x,y,0'),
        (8, 'x,y,1/2'),
        (16, 'x, y, z'),
    )
}
