# Generated Thu Oct 06 17:12:26 2016
d = {}
d['1'] = {
    'number': 68,
    'setting': '1',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k=2n',
        'hk0: h=2n',
        'h0l: h+l=2n',
        '0kl: k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 90 deg (h+l)',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, -z+1/2',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
        'x, y+1/2, -z+1/2',
        '-x, y+1/2, z+1/2',
        'x, -y+1/2, z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['2'] = {
    'number': 68,
    'setting': '2',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k=2n',
        'hk0: h=2n',
        'h0l: h+l=2n',
        '0kl: k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, z',
        'x, -y+1/2, -z+1/2',
        '-x, y, -z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['1ba-c'] = {
    'number': 68,
    'setting': '1ba-c',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k=2n',
        'hk0: h=2n',
        'h0l: h+l=2n',
        '0kl: k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 90 deg (h+l)',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, -z+1/2',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
        'x, y+1/2, -z+1/2',
        '-x, y+1/2, z+1/2',
        'x, -y+1/2, z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['2ba-c'] = {
    'number': 68,
    'setting': '2ba-c',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k=2n',
        'hk0: h=2n',
        'h0l: h+l=2n',
        '0kl: k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.0],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, z',
        'x, -y, -z+1/2',
        '-x, y+1/2, -z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['1cab'] = {
    'number': 68,
    'setting': '1cab',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: k+l=2n',
        'hk0: h+k=2n',
        'h0l: h+l=2n',
        '0kl: k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 90 deg (h+k)',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x+1/2, -y, -z+1/2',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
        'x+1/2, y, -z+1/2',
        '-x+1/2, y, z+1/2',
        'x+1/2, -y, z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['2cab'] = {
    'number': 68,
    'setting': '2cab',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: k+l=2n',
        'hk0: h+k=2n',
        'h0l: h+l=2n',
        '0kl: k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x+1/2, -y, z',
        'x, -y, -z+1/2',
        '-x+1/2, y, -z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['1-cba'] = {
    'number': 68,
    'setting': '1-cba',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: k+l=2n',
        'hk0: h+k=2n',
        'h0l: h+l=2n',
        '0kl: k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 90 deg (h+k)',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x+1/2, -y, -z+1/2',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
        'x+1/2, y, -z+1/2',
        '-x+1/2, y, z+1/2',
        'x+1/2, -y, z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['2-cba'] = {
    'number': 68,
    'setting': '2-cba',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: k+l=2n',
        'hk0: h+k=2n',
        'h0l: h+l=2n',
        '0kl: k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x+1/2, -y, z+1/2',
        'x, -y, -z+1/2',
        '-x+1/2, y, -z',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['1bca'] = {
    'number': 68,
    'setting': '1bca',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+l=2n',
        'hk0: h+k=2n',
        'h0l: h=2n',
        '0kl: k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 90 deg (h+k)',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.0, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, -z+1/2',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
        'x, y+1/2, -z+1/2',
        '-x, y+1/2, z+1/2',
        'x, -y+1/2, z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['2bca'] = {
    'number': 68,
    'setting': '2bca',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+l=2n',
        'hk0: h+k=2n',
        'h0l: h=2n',
        '0kl: k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.0, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, z+1/2',
        'x, -y+1/2, -z',
        '-x, y, -z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['1a-cb'] = {
    'number': 68,
    'setting': '1a-cb',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+l=2n',
        'hk0: h+k=2n',
        'h0l: h=2n',
        '0kl: k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 90 deg (h+k)',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.0, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, -z+1/2',
        '-x, -y, z',
        'x, -y, -z',
        '-x, y, -z',
        'x, y+1/2, -z+1/2',
        '-x, y+1/2, z+1/2',
        'x, -y+1/2, z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}

d['2a-cb'] = {
    'number': 68,
    'setting': '2a-cb',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+l=2n',
        'hk0: h+k=2n',
        'h0l: h=2n',
        '0kl: k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.0, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, z',
        'x, -y+1/2, -z+1/2',
        '-x, y, -z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,1/4,1/4'),
        (4, '0,1/4,-1/4'),
        (8, '1/4,-1/4,0'),
        (8, '0,0,0'),
        (8, 'x,1/4,1/4'),
        (8, '0,y,1/4'),
        (8, '0,1/4,z'),
        (8, '1/4,0,z'),
        (16, 'x, y, z'),
    )
}
