# Generated Thu Oct 06 17:12:27 2016
d = {}
d[''] = {
    'number': 72,
    'setting': '',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k+l=2n',
        'h0l: h=2n',
        '0kl: k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x, -y, z',
        'x, -y, -z+1/2',
        '-x, y, -z+1/2',
    ),
    'wyckoff_positions' : (
        (4, '0,0,1/4'),
        (4, '1/2,0,1/4'),
        (4, '0,0,0'),
        (4, '1/2,0,0'),
        (8, '1/4,1/4,1/4'),
        (8, 'x,0,1/4'),
        (8, '0,y,1/4'),
        (8, '0,0,z'),
        (8, '0,1/2,z'),
        (8, 'x,y,0'),
        (16, 'x, y, z'),
    )
}

d['cab'] = {
    'number': 72,
    'setting': 'cab',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k+l=2n',
        'hk0: h=2n',
        'h0l: h=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x+1/2, -y, z',
        'x, -y, -z',
        '-x+1/2, y, -z',
    ),
    'wyckoff_positions' : (
        (4, '0,0,1/4'),
        (4, '1/2,0,1/4'),
        (4, '0,0,0'),
        (4, '1/2,0,0'),
        (8, '1/4,1/4,1/4'),
        (8, 'x,0,1/4'),
        (8, '0,y,1/4'),
        (8, '0,0,z'),
        (8, '0,1/2,z'),
        (8, 'x,y,0'),
        (16, 'x, y, z'),
    )
}

d['bca'] = {
    'number': 72,
    'setting': 'bca',
    'point_group': 'mmm',
    'laue_group': 'mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': None,
    'centrosymmetric': True,
    'enantiomorphic': False,
    'chiral': False,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k+l=2n',
        'hk0: h=2n',
        '0kl: k=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hk0: e=4',
        'h0l: e=4',
        '0kl: e=4',
        'h00: e=8',
        '0k0: e=8',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hkl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-x, -y+1/2, z',
        'x, -y+1/2, -z',
        '-x, y, -z',
    ),
    'wyckoff_positions' : (
        (4, '0,0,1/4'),
        (4, '1/2,0,1/4'),
        (4, '0,0,0'),
        (4, '1/2,0,0'),
        (8, '1/4,1/4,1/4'),
        (8, 'x,0,1/4'),
        (8, '0,y,1/4'),
        (8, '0,0,z'),
        (8, '0,1/2,z'),
        (8, 'x,y,0'),
        (16, 'x, y, z'),
    )
}
