# Generated Thu Oct 06 17:12:29 2016
d = {}
d[''] = {
    'number': 97,
    'setting': '',
    'point_group': '422',
    'laue_group': '4/mmm',
    'order': 16,
    'order_p': 8,
    'unique_axis': 'z',
    'centrosymmetric': False,
    'enantiomorphic': False,
    'chiral': True,
    'obverse': False,
    'reflection_conditions': (
        'hkl: h+k+l=2n',
    ),
    'enhanced_reflections': (
        'hkl: e=2',
        'hh0: e=4',
        'h00: e=4',
        'h-h0: e=4',
        '0k0: e=4',
        '00l: e=8',
    ),
    'phase_restrictions': (
        'hhl: 0 deg',
        'hk0: 0 deg',
        'h0l: 0 deg',
        'h-hl: 0 deg',
        '0kl: 0 deg',
    ),
    'centering_vectors': (
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.5],
    ),
    'symops': (
        'x, y, z',
        '-y, x, z',
        '-x, -y, z',
        'y, -x, z',
        'x, -y, -z',
        '-x, y, -z',
        'y, x, -z',
        '-y, -x, -z',
    ),
    'wyckoff_positions' : (
        (2, '0,0,0'),
        (2, '0,0,1/2'),
        (4, '0,1/2,0'),
        (4, '0,1/2,1/4'),
        (4, '0,0,z'),
        (8, '0,1/2,z'),
        (8, '1/2*x+1/2*y,1/2*x+1/2*y,0'),
        (8, 'x,0,0'),
        (8, 'x,0,1/2'),
        (8, '1/2*x+1/2*y-1/4,1/2*x+1/2*y+1/4,1/4'),
        (16, 'x, y, z'),
    )
}
